COMMAND_RUN = "RUN"
COMMAND_COPY = "COPY"
COMMAND_SQL = "SQL"

EVENT_GIT_PUSH = 'push'

CONNECTION_SQLITE = "SQLITE"
CONNECTION_MYSQL = "MYSQL"
CONNECTION_POSTGRESQL = "POSTGRESQL"

CONFIGURATION_FILE_NAME = "george.yml"

LOG_MAX_SIZE_MEGA_BYTES = 10
LOG_FILE_NAME = "george.log"
